### ISSUE TITLE
Image is too large to be transformed, or image size couldn't be determined.

### ISSUE THREAD

**Issue by martabitbrain** [martabitbrain/directus-extension-sane-image-size#7]
Error found after trying to upload an image on Directus 10.10.7

```
 [13:25:15.972] WARN: Image is too large to be transformed, or image size couldn't be determined.
 [13:25:15.972] WARN: An error was thrown while executing action "files.upload"
 [13:25:15.972] WARN: Illegal asset transformation.
     err: {
       "type": "",
       "message": "Illegal asset transformation.",
       "stack":
           DirectusError: Illegal asset transformation.
               at AssetsService.getAsset (file:///var/www/web-backend/node_modules/@directus/api/dist/services/assets.js:109:23)
               at async EventEmitter.<anonymous> (file:///var/www/web-backend/node_modules/directus-extension-sane-image-size/dist/index.js?t=1713792129986:1:55700)
               at async Promise.all (index 0)
       "name": "DirectusError",
       "extensions": {
         "invalidTransformations": [
           "width",
           "height"
         ]
       },
       "code": "ILLEGAL_ASSET_TRANSFORMATION",
       "status": 400
     }
```

**Comment by robinsonjohn** [comment]
I can confirm the same error using Directus 10.11.0 Docker self-hosted. The image is never resized.

```
2024-05-16 16:33:12  | [20:33:11.866] WARN: Image is too large to be transformed, or image size couldn't be determined.
2024-05-16 16:33:12  | [20:33:11.867] DEBUG: Illegal asset transformation.
2024-05-16 16:33:12  |     err: {
2024-05-16 16:33:12  |       "type": "",
2024-05-16 16:33:12  |       "message": "Illegal asset transformation.",
2024-05-16 16:33:12  |       "stack":
2024-05-16 16:33:12  |           DirectusError: Illegal asset transformation.
2024-05-16 16:33:12  |               at AssetsService.getAsset (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/services/assets.js:109:23)
2024-05-16 16:33:12  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-16 16:33:12  |               at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/controllers/assets.js:154:36
2024-05-16 16:33:12  |       "name": "DirectusError",
2024-05-16 16:33:12  |       "extensions": {
2024-05-16 16:33:12  |         "invalidTransformations": [
2024-05-16 16:33:12  |           "width",
2024-05-16 16:33:12  |           "height"
2024-05-16 16:33:12  |         ]
2024-05-16 16:33:12  |       },
2024-05-16 16:33:12  |       "code": "ILLEGAL_ASSET_TRANSFORMATION",
2024-05-16 16:33:12  |       "status": 400
2024-05-16 16:33:12  |     }
```

**Comment by NilsBaumgartner1994** [comment]
Uploaded a 16mb image: 8192x5464 pixels

**Comment by martabitbrain** [comment]
Hi @NilsBaumgartner1994 

Browsing directus' code searching for the source of the error, I discovered that there is an environment variable that limits the maximum image dimension that can be uploaded. Please check ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION. It's 6000 by default. https://docs.directus.io/self-hosted/config-options.html#assets

This is the specific Directus code that is throwing the error: https://github.com/directus/directus/blob/45ae21589711ae639eea23de25536db1c727996b/api/src/services/assets.ts#L144-L152

Cheers!

**Comment by NilsBaumgartner1994** [comment]
Cheers mate,Thank you :-)Beste Grüße,Nils BaumgartnerAm 31.05.2024 um 09:18 schrieb Marta ***@***.***>:﻿
Hi @NilsBaumgartner1994
Browsing directus' code searching for the source of the error, I discovered that there is an environment variable that limits the maximum image dimension that can be uploaded. Please check ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION. It's 6000 by default. https://docs.directus.io/self-hosted/config-options.html#assets
This is the specific Directus code that is throwing the error: https://github.com/directus/directus/blob/45ae21589711ae639eea23de25536db1c727996b/api/src/services/assets.ts#L144-L152
Cheers!

**Comment by NilsBaumgartner1994** [comment]
LOL, why was I able to upload an image anyway this big?Beste Grüße,Nils BaumgartnerAm 31.05.2024 um 10:06 schrieb Nils Baumgartner ***@***.***>:﻿Cheers mate,Thank you :-)Beste Grüße,Nils BaumgartnerAm 31.05.2024 um 09:18 schrieb Marta ***@***.***>:﻿
Hi @NilsBaumgartner1994
Browsing directus' code searching for the source of the error, I discovered that there is an environment variable that limits the maximum image dimension that can be uploaded. Please check ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION. It's 6000 by default. https://docs.directus.io/self-hosted/config-options.html#assets
This is the specific Directus code that is throwing the error: https://github.com/directus/directus/blob/45ae21589711ae639eea23de25536db1c727996b/api/src/services/assets.ts#L144-L152
Cheers!
